[project]
name = "uv-validation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyspark==3.5.4",
    "ruff>=0.8.4",
]
